title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# _config.yml
nav:
  - title: "Inicio"
    path: index.md
  - title: "PROGRAMACION"
    path: PROGRAMACION.md
  - title: "BASES DE DATOS"
    path: BDA.md
  - title: "ENTORNOS DE DESARROLLO"
    path: ENDES.md
  - title: "INGLES"
    path: ENG.md
  - title: "ITINERARIO PERSONAL"
    path: ITIPERSONAL.md
  - title: "SISTEMAS INFORMATICOS"
    path: SISINF.md 
