title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# _config.yml
nav:
  - title: "Inicio"
    path: index.md
    weight: 1
  - title: "PROGRAMACION"
    path: PROGRAMACION.md
    weight: 2
  - title: "BASES DE DATOS"
    path: BDA.md
    weight: 3
  - title: "ENTORNOS DE DESARROLLO"
    path: ENDES.md
    weight: 4
  - title: "INGLES"
    path: ENG.md
    weight: 5
  - title: "ITINERARIO PERSONAL"
    path: ITIPERSONAL.md
    weight: 6
  - title: "SISTEMAS INFORMATICOS"
    path: SISINF.md 
    weight: 7
