title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# _config.yml
nav:
  - title: "Inicio"
    path: index.md
  - title: "PROGRAMACION"
    path: PROGRAMACION.md
  - title: "BDA"
    path: BDA.md
  - title: "ENDES"
    path: ENDES.md
  - title: "ENG"
    path: ENG.md
  - title: "ITIPERSONAL"
    path: ITIPERSONAL.md
  - title: "SISINF"
    path: SISINF.md 
