title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# _config.yml
nav:
  - title: "1.Home"
    path: index.md
    
  - title: "2.PROGRAMACION"
    path: PROGRAMACION.md
    
  - title: "3.BASES DE DATOS"
    path: BDA.md
    
  - title: "4.ENTORNOS DE DESARROLLO"
    path: ENDES.md
    
  - title: "5.INGLES"
    path: ENG.md
    
  - title: "6.ITINERARIO PERSONAL"
    path: ITIPERSONAL.md
   
  - title: "7.SISTEMAS INFORMATICOS"
    path: SISINF.md 
    
